program ::= {query} ;
query   ::= [ddl_stmt | dml_stmt] (';')+ ;

// DDL Statements
ddl_stmt             ::= create_database_stmt | create_table_stmt | alter_table_stmt
                         | drop_database_stmt | drop_table_stmt ;
create_database_stmt ::= 'CREATE DATABASE' database_name ;
create_table_stmt    ::= 'CREATE TABLE' table_name table_def ;
alter_table_stmt     ::= 'ALTER TABLE' table_name
                         (('ADD' alter_table_add_list) | ('DROP' alter_table_drop_list)) ;
drop_database_stmt   ::= 'DROP DATABASE' database_name_list_ ;
drop_table_stmt      ::= 'DROP TABLE' table_name_list_ ;

table_def        ::= '(' table_def_element_list_ ')' ;
column_def       ::= column_name data_type ;
table_constraint ::= ['CONSTRAINT' constraint_name] (primary_key | foreign_key) ;

alter_table_add_list  ::= table_def_element_list_ ;
alter_table_drop_list ::= alter_table_drop_element_ {',' alter_table_drop_element_} ;

// DML Statements

dml_stmt    ::= insert_stmt | update_stmt | delete_stmt
insert_stmt ::= 'INSERT' ['INTO'] table_name ['(' column_name_list_ ')']
                'VALUES' '(' insert_values_list_ ')';
update_stmt ::= 'UPDATE' table_name 'SET' update_column_list_ ['WHERE' condition] ;
delete_stmt ::= 'DELETE' ['FROM'] table_name 'WHERE' condition ;

// Helpers

name_list_                   ::= name {',' name} ;
table_def_element_list_      ::= table_def_element_ {',' table_def_element_} ;
table_def_element_           ::= column_def | table_constraint ;
column_name_list_            ::= column_name {',' column_name} ;
constraint_name_list_        ::= constraint_name {',' constraint_name} ;
alter_table_drop_element_    ::= alter_table_drop_column_ | alter_table_drop_constraint_ ;
alter_table_drop_column_     ::= 'COLUMN' column_name_list_ ;
alter_table_drop_constraint_ ::= 'CONSTRAINT' constraint_name_list_ ;
database_name_list_          ::= database_name {',' database_name} ;
table_name_list_             ::= table_name {',' table_name} ;
insert_values_list_          ::= insert_values_element_ {',' insert_values_element_} ;
insert_values_element_       ::= '(' ('NULL' | expr) ')' ;
update_column_list_          ::= update_column_element_ {',' update_column_element_} ;
update_column_element_       ::= column_name '=' ('NULL' | expr) ;

// Basic Statements

primary_key ::= 'PRIMARY KEY' '(' column_name_list_ ')' ;
foreign_key ::= 'FOREIGN KEY' '(' column_name_list_ ')' reference ;
reference   ::= 'REFERENCES' table_name ['(' column_name_list_ ')'] ;

database_name   ::= name ;
table_name      ::= name ;
column_name     ::= name ;
constraint_name ::= identifier ;
name            ::= identifier {'.' identifier} ;
data_type       ::= 'float' | ('int' | 'integer') | 'varchar' | 'char' ;

// Conditions

condition     ::= or_condition ;
or_condition  ::= and_condition ['OR' and_condition] ;
and_condition ::= not_condition ['AND' not_condition] ;
not_condition ::= 'NOT' predicate ;
predicate     ::= expr binary_operator_ expr ;
expr          ::= name_list_ | (unary_operator_ expr) | ('(' expr ')') | string | math_expr ;

// Math Expressions (PEG)

math_expr ::= sum ;
sum       ::= product [('+' | '-') product] ;
product   ::= power [('*' | '/') power] ;
power     ::= value ['^' power] ;
value     ::= 'regexp:[0-9]+' | ('(' math_expr ')') ;

// Base

identifier ::= "regexp:[_a-zA-z0-9]+" ;
string     ::= ("'" string_ "'") | ('"' string_ '"') ;

string_          ::= 'regexp: [a-zA-z0-9_\-+*/=!.<>]'
binary_operator_ ::= '!=' | '=' | '!>' | '>' | '>=' | '!<' | '<' | '<=' | '<>' ;
unary_operator_  ::= '+' | '-' ;
