name: 'Build test'

on:
  push:
  pull_request:
    types:
    - reopened
    - ready_for_review
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: SetUp
      run: sudo apt install graphviz
    
    - name: Build
      run: cmake -S . -B build
      
    - name: Make
      run: cd build && cmake --build .
      
    - name: Test
      run: cd build && ctest
