name: 'Build test'

on:
  push:
  pull_request:
    types:
    - reopened
    - ready_for_review
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install graphviz
    - name: Configure
      run: cmake -S . -B build
    - name: Build
      run: cd build && cmake --build .
    - name: Unit tests
      run: cd build && ctest
